added momentum units
sddale/csm-units pull request #58
Opened 2023-11-13 22:22 UTC by kavjey

2023-11-13 22:54 UTC, sddale commented
Class names should always be upper camel case and without shortened unit names. i.e. `Kilogram`

Please correct.

2023-11-14 05:31 UTC, sddale commented
Changes aren't compiling. Needs correction.

2023-11-15 19:26 UTC, SanderSchott requested changes
Take a look at the comments for each individual file. These changes should be implemented before merging.

2023-11-15 19:26 UTC, SanderSchott commented on include/csm_units/momentum.hpp
Included files need to be changed to the new name of the files.

2023-11-15 19:26 UTC, SanderSchott commented on source/csm_units/named_units/momentum/kilogram_meters_per_second.hpp
Documentation comment needs to change "Momentum" link name to "Kilogram Meter Per Second". Also using declaration name should be fully spelled out. Instead of `KgMPS` say `KilogramMeterPerSecond`.

2023-11-15 19:26 UTC, SanderSchott commented on source/csm_units/named_units/momentum/slug_feet_per_second.hpp
Same comments as the `kilogram_meters_per_second.hpp` file. Documentation comment should be updated and using declaration name should also be updated.

2023-11-16 19:33 UTC, SanderSchott requested changes
There are a couple small changes still. Take a look at the comments to the respective files.

2023-11-16 19:33 UTC, SanderSchott commented on source/csm_units/named_units/momentum/kilogram_meters_per_second.hpp
> +using KilogramMeterPerSecond = Unit<Momentum, "kgmps", double>;
The the string literal inside the Unit class template should be `"kgm/s"`
I.e `Unit<Momentum, "kgm/s", double>;`

2023-11-16 19:33 UTC, SanderSchott commented on source/csm_units/named_units/momentum/kilogram_meters_per_second.hpp
You still want to have the wikipedia explanation link as part of the documentation. Just the link alias needed to change. You should also fully write out the unit name in the brief section. The below would be an example of what you could have for this file's documentation.
```
/**  \file kilogram_meters_per_second.hpp
 *   \brief This file is used to define the Momentum SI unit Kilogram Meter Per Second
 *
 *   The following wikipedia page can explain <a
 * href="https://en.wikipedia.org/wiki/Momentum">Kilogram Meter Per Second</a> if needed.
 */
```

2023-11-16 19:33 UTC, SanderSchott commented on source/csm_units/named_units/momentum/slug_feet_per_second.hpp
As with the `kilogram_meters_per_second.hpp` the documentation and string literal for unit should be updated here as well. Same general idea, just update with Slug Feet Per Second instead. The Momentum link should be fine because it also references the units Slug Feet Per Second.

The string literal inside of the Unit class template should be changed to `slugft/s` as well.

2023-11-16 19:53 UTC, SanderSchott approved these changes

2023-11-16 19:55 UTC, merged